sudo: required

services:
  - docker

before_install:
  - docker image build -t gloompi/kubernetes-image -f Dockerfile.dev .

script:
  - docker container run gloompi/kubernetes-image yarn run test --watchAll=false
